local M = {}

M.lspkind = {
  File          = " ",
  Module        = " ",
  Namespace     = " ",
  Package       = " ",
  Class         = " ",
  Method        = " ",
  Property      = " ",
  Field         = " ",
  Constructor   = " ",
  Enum          = " ",
  Interface     = " ",
  Function      = " ",
  Variable      = " ",
  Constant      = " ",
  String        = " ",
  Number        = " ",
  Boolean       = " ",
  Array         = " ",
  Object        = " ",
  Key           = " ",
  Null          = "ﳠ ",
  EnumMember    = " ",
  Struct        = " ",
  Event         = " ",
  Operator      = " ",
  TypeParameter = " ",
  Text          = " ",
  Unit          = "塞",
  Watch         = " ",
  Calendar      = " ",
  Snippet       = " ",
  Table         = " ",
  Tag           = " ",
  Value         = " ",
  Keyword       = " ",
  Reference     = " ",
  Color         = " ",
  Folder        = " ",
}

return M
